[package]
name = "stella-proto"
description = "Pure Stella wire protocol codec"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
stella-common = { path = "../stella-common" }

[lints]
workspace = true
